# -*- coding: utf-8 -*-
"""SQLite3_Employee

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q4i3Lk1-9eP7dJH_4T3S1W6BPkCwJYjG
"""

import sqlite3

class Employee:
  def __init__(self, first, last, pay):
    self.first = first
    self.last = last
    self.pay = pay

conn = sqlite3.connect(':memory:')

c = conn.cursor()

c.execute("""CREATE TABLE employees (
             first text,
             last text,
             pay integer
             )""")

def insert_emp(emp):
  with conn:
    c.execute("INSERT INTO employees VALUES (:first, :last, :pay)", {'first': emp.first, 'last': emp.last, 'pay': emp.pay})

def get_emps_by_name(lastname):
  c.execute("SELECT * FROM employees WHERE last=:last", {'last': lastname})
  return c.fetchall()

def update_pay(emp, pay):
  with conn:
    c.execute("""UPDATE employees SET pay = :pay
                WHERE first = :first AND last = :last""",
              {'first': emp.first, 'last': emp.last, 'pay': pay})

def remove_emp(emp):
  with conn:
    c.execute("DELETE from employees WHERE first = :first AND last = :last", 
              {'first': emp.first, 'last': emp.last})

emp_1 = Employee('John', 'Doe', 80000)
emp_2 = Employee('Jane', 'Doe', 90000)

insert_emp(emp_1)
insert_emp(emp_2)

emps = get_emps_by_name('Doe')
print(emps)

update_pay(emp_2, 95000)
remove_emp(emp_1)

emps = get_emps_by_name('Doe')
print(emps)

conn.close()